minimum_prek_version: '0.2.28'


ci:
  autofix_prs: true
  autofix_commit_msg: "[pre-commit.ci] auto fixes from pre-commit hooks [skip ci]"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
        exclude: ^ui/tsconfig.*\.json$
      - id: check-toml
      - id: check-yaml
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-ast

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    language: python
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    language: rust
    hooks:
      - id: fmt
        args: ["--check", "--manifest-path", "src-tauri/Cargo.toml", "--"]
      - id: clippy
        args: ["--manifest-path", "src-tauri/Cargo.toml", "--", "-D", "warnings"]
